# Generated by Django 5.0.6 on 2026-08-25 15:04

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='اسم المستخدم')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('role', models.CharField(choices=[('manager', 'المدير'), ('supervisor', 'المشرف'), ('accountant', 'المحاسب'), ('cashier', 'الكاشير')], default='cashier', max_length=20, verbose_name='الدور')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/', verbose_name='الصورة الشخصية')),
                ('id_card_front', models.ImageField(blank=True, null=True, upload_to='id_cards/%Y/%m/', verbose_name='صورة البطاقة الأمامية')),
                ('id_card_back', models.ImageField(blank=True, null=True, upload_to='id_cards/%Y/%m/', verbose_name='صورة البطاقة الخلفية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, verbose_name='موظف')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدير عام')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الانضمام')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخر دخول')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('view', 'عرض'), ('export', 'تصدير'), ('approve', 'موافقة'), ('reject', 'رفض')], max_length=20, verbose_name='الإجراء')),
                ('entity_type', models.CharField(max_length=50, verbose_name='نوع الكيان')),
                ('entity_id', models.CharField(blank=True, max_length=100, verbose_name='معرف الكيان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح المستخدم')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
            ],
            options={
                'verbose_name': 'سجل النشاط',
                'verbose_name_plural': 'سجلات الأنشطة',
                'ordering': ['-timestamp'],
            },
        ),
    ]
