# Generated by Django 5.0.6 on 2026-08-25 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوردية')),
                ('shift_type', models.CharField(choices=[('morning', 'وردية صباحية'), ('evening', 'وردية مسائية'), ('night', 'وردية ليلية'), ('custom', 'وردية مخصصة')], default='morning', max_length=20, verbose_name='نوع الوردية')),
                ('start_time', models.TimeField(verbose_name='وقت البدء')),
                ('end_time', models.TimeField(verbose_name='وقت الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='branches.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'وردية عمل',
                'verbose_name_plural': 'ورديات العمل',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الفتح')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة'), ('pending', 'بانتظار المراجعة'), ('reopened', 'تم إعادة فتحها')], default='open', max_length=20, verbose_name='الحالة')),
                ('closure_notes', models.TextField(blank=True, verbose_name='ملاحظات الإغلاق')),
                ('reopened_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت إعادة الفتح')),
                ('reopen_reason', models.TextField(blank=True, verbose_name='سبب إعادة الفتح')),
                ('total_transactions', models.PositiveIntegerField(default=0, verbose_name='إجمالي العمليات')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المبالغ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_sessions', to='branches.branch', verbose_name='الفرع')),
                ('cashier', models.ForeignKey(limit_choices_to={'role': 'cashier'}, on_delete=django.db.models.deletion.PROTECT, related_name='shift_sessions', to=settings.AUTH_USER_MODEL, verbose_name='الكاشير')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_sessions', to=settings.AUTH_USER_MODEL, verbose_name='تم الإغلاق بواسطة')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_sessions', to=settings.AUTH_USER_MODEL, verbose_name='تم إعادة الفتح بواسطة')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='shifts.shift', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'جلسة وردية',
                'verbose_name_plural': 'جلسات الورديات',
                'ordering': ['-opened_at'],
            },
        ),
    ]
