# Generated by Django 5.0.6 on 2026-08-25 15:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('shifts', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(editable=False, max_length=100, unique=True, verbose_name='معرف العملية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('payment_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الدفع')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='رقم مرجعي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('notification_image', models.ImageField(blank=True, null=True, upload_to='transactions/notifications/%Y/%m/%d/', verbose_name='صورة إشعار الدفع')),
                ('status', models.CharField(choices=[('pending', 'معلقة'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة'), ('refunded', 'مسترجعة')], default='completed', max_length=20, verbose_name='الحالة')),
                ('sync_status', models.CharField(choices=[('synced', 'متزامن'), ('pending', 'بانتظار المزامنة'), ('failed', 'فشلت المزامنة')], default='synced', max_length=20, verbose_name='حالة المزامنة')),
                ('is_offline', models.BooleanField(default=False, verbose_name='تمت بدون اتصال')),
                ('device_id', models.CharField(blank=True, max_length=100, verbose_name='معرف الجهاز')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المزامنة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False, verbose_name='تم التعديل')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التعديل')),
                ('edit_reason', models.TextField(blank=True, verbose_name='سبب التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحذف')),
                ('deletion_reason', models.TextField(blank=True, verbose_name='سبب الحذف')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='branches.branch', verbose_name='الفرع')),
                ('cashier', models.ForeignKey(limit_choices_to={'role': 'cashier'}, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='الكاشير')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_transactions', to=settings.AUTH_USER_MODEL, verbose_name='تم الحذف بواسطة')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_transactions', to=settings.AUTH_USER_MODEL, verbose_name='تم التعديل بواسطة')),
                ('shift_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='shifts.shiftsession', verbose_name='جلسة الوردية')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet', verbose_name='المحفظة')),
            ],
            options={
                'verbose_name': 'عملية دفع',
                'verbose_name_plural': 'عمليات الدفع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('restore', 'استعادة'), ('view', 'عرض')], max_length=20, verbose_name='الإجراء')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='البيانات القديمة')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='البيانات الجديدة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transactions.transaction', verbose_name='العملية')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل عملية',
                'verbose_name_plural': 'سجلات العمليات',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='transaction_transac_fee96f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_67ce7b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['cashier', 'created_at'], name='transaction_cashier_b16c11_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['branch', 'created_at'], name='transaction_branch__1d3a65_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'created_at'], name='transaction_wallet__4e065b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['shift_session'], name='transaction_shift_s_b80c1a_idx'),
        ),
    ]
