# Generated by Django 5.0.6 on 2026-08-25 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم المحفظة')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='اسم المحفظة (إنجليزي)')),
                ('wallet_code', models.CharField(blank=True, max_length=50, verbose_name='كود المحفظة')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم المحفظة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='wallets/logos/%Y/%m/', verbose_name='الشعار')),
                ('keywords', models.TextField(blank=True, help_text='أدخل الكلمات المفتاحية مفصولة بفواصل (مثال: جيب, jaib, محفظة جيب, jaib wallet)', verbose_name='الكلمات المفتاحية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='branches.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محفظة إلكترونية',
                'verbose_name_plural': 'المحافظ الإلكترونية',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'branch')},
            },
        ),
    ]
